// Team members list - Single source of truth for all employee names
// Update this list when team members change
export const TEAM_MEMBERS = [
  "Julianne",
  "Eric",
  "Quinn",
  "Kavan",
  "Victor",
  "Eniko",
  "Luiza",
  "Michelle",
  "Maria",
  "Payton",
  "Seamus",
  "Sofia",
  "Reddy",
  "Noah",
  "Richard",
  "Melissa",
  "Kal",
  "Manish",
  "Towhid",
  "Jahid",
  "Juliana",
  "Ajan",
  "Luigi",
  "Charlotte",
  "Irina",
  "Rachael",
  "Brogan",
  "Mirlley",
  "Samaneh",
  "Sam M",
  "Sam J",
  "Salma",
  "Evan",
  "Raha",
  "Alan",
  "Mahek",
  "Jeffrey",
  "Alexandra",
  "Hisham",
  "Spencer",
  "Rodrigo",
  "Kiera",
  "Jade",
  "Laura",
  "Team Rocket",
]

// Email to name mapping for RACI filtering
// Maps @rayleighsolartech.com emails to display names
export const EMAIL_TO_NAME_MAP = {
  "julianne.hillyer@rayleighsolartech.com": "Julianne",
  "eric.bergmann@rayleighsolartech.com": "Eric",
  "quinn.smith-huphman@rayleighsolartech.com": "Quinn",
  "kavan.patel@rayleighsolartech.com": "Kavan",
  "victor.prajapati@rayleighsolartech.com": "Victor",
  "eniko.zsoldos@rayleighsolartech.com": "Eniko",
  "luiza.correa@rayleighsolartech.com": "Luiza",
  "michelle.pellerin@rayleighsolartech.com": "Michelle",
  "maria.judy@rayleighsolartech.com": "Maria",
  "payton.brown@rayleighsolartech.com": "Payton",
  "seamus.macinnes@rayleighsolartech.com": "Seamus",
  "sofia.jorge@rayleighsolartech.com": "Sofia",
  "reddy@rayleighsolartech.com": "Reddy",
  "noah.cyr@rayleighsolartech.com": "Noah",
  "richard.kapuscinski@rayleighsolartech.com": "Richard",
  "melissa.ball@rayleighsolartech.com": "Melissa",
  "kal.hendel@rayleighsolartech.com": "Kal",
  "manish.jadhav@rayleighsolartech.com": "Manish",
  "towhid.chowdhury@rayleighsolartech.com": "Towhid",
  "jahid.anowar@rayleighsolartech.com": "Jahid",
  "juliana.ramireznarino@rayleighsolartech.com": "Juliana",
  "ajan.ramachandran@rayleighsolartech.com": "Ajan",
  "luigi.castriotta@rayleighsolartech.com": "Luigi",
  "charlotte.clegg@rayleighsolartech.com": "Charlotte",
  "irina.valitova@rayleighsolartech.com": "Irina",
  "rachael.fashakin@rayleighsolartech.com": "Rachael",
  "brogan.obrien@rayleighsolartech.com": "Brogan",
  "mirlley.mendonca@rayleighsolartech.com": "Mirlley",
  "samaneh.aynehband@rayleighsolartech.com": "Samaneh",
  "samuel.march@rayleighsolartech.com": "Sam M",
  "sam.j@rayleighsolartech.com": "Sam J",
  "salma.zouhair@rayleighsolartech.com": "Salma",
  "evan.fitzpatrick@rayleighsolartech.com": "Evan",
  "raha.khosravi@rayleighsolartech.com": "Raha",
  "alan.kaplan@rayleighsolartech.com": "Alan",
  "mahek.kamani@rayleighsolartech.com": "Mahek",
  "jeffrey.chen@rayleighsolartech.com": "Jeffrey",
  "alexandra.scott@rayleighsolartech.com": "Alexandra",
  "hisham.hamza@rayleighsolartech.com": "Hisham",
  "spencer.brown-sweeting@rayleighsolartech.com": "Spencer",
  "rodrigo.machado@rayleighsolartech.com": "Rodrigo",
  "kiera.chang@rayleighsolartech.com": "Kiera",
  "jade@rayleighsolartech.com": "Jade",
  "laura@rayleighsolartech.com": "Laura",
  // For testing in local dev
  "dev@rayleighsolartech.com": "Manish", // Default test user
}

// Helper function to get name from email
export const getNameFromEmail = (email) => {
  if (!email) return null;
  return EMAIL_TO_NAME_MAP[email.toLowerCase()] || null;
}
